In [1]:
import seaborn as sns
import numpy as np
import pandas as pd

### loading dataset which will be analysized

In [2]:
df = sns.load_dataset('titanic')

### looking around dataset (first, second, any observation)

In [3]:
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class   
0         0       3    male  22.0      1      0   7.2500        S  Third  \
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [5]:
df.tail()

survived  pclass     sex   age  sibsp  parch   fare embarked   class   
886         0       2    male  27.0      0      0  13.00        S  Second  \
887         1       1  female  19.0      0      0  30.00        S   First   
888         0       3  female   NaN      1      2  23.45        S   Third   
889         1       1    male  26.0      0      0  30.00        C   First   
890         0       3    male  32.0      0      0   7.75        Q   Third   

       who  adult_male deck  embark_town alive  alone  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True

In [6]:
df.sample(10)

survived  pclass     sex   age  sibsp  parch     fare embarked   class   
494         0       3    male  21.0      0      0   8.0500        S   Third  \
491         0       3    male  21.0      0      0   7.2500        S   Third   
423         0       3  female  28.0      1      1  14.4000        S   Third   
8           1       3  female  27.0      0      2  11.1333        S   Third   
178         0       2    male  30.0      0      0  13.0000        S  Second   
375         1       1  female   NaN      1      0  82.1708        C   First   
401         0       3    male  26.0      0      0   8.0500        S   Third   
407         1       2    male   3.0      1      1  18.7500        S  Second   
771         0       3    male  48.0      0      0   7.8542        S   Third   
218         1       1  female  32.0      0      0  76.2917        C   First   

       who  adult_male deck  embark_town alive  alone  
494    man        True  NaN  Southampton    no   True  
491    man        True  NaN  Southampton    no   True  
423  woman       False  NaN  Southampton    no  False  
8    woman       False  NaN  Southampton   yes  False  
178    man        True  NaN  Southampton    no   True  
375  woman       False  NaN    Cherbourg   yes  False  
401    man        True  NaN  Southampton    no   True  
407  child       False  NaN  Southampton   yes  False  
771    man        True  NaN  Southampton    no   True  
218  woman       False    D    Cherbourg   yes   True

This data set is about to Titanic ship which sank. You will find only passengers info not craw bought ticket.

* survived -> State of survive? (0 : No , 1: Yes)

/ alive -> Whether the traveler survived (no , yes)

* pclass -> Socio-economic class (1 = Upper class; 2 = Middle class; 3 = Lower class)

/ class -> Passenger class(First(Best) , Second, Third(Worst))

* sex -> Passenger’s gender (Male , Female)

*  age -> Passenger’s age (0.42 (Babies under 1 year old) , 80)

/ who -> Distribution of passenger (Child, Man, Woman)

/ adult_male -> Whether the passenger is a adult man (True , False)

* sibsp -> The number of brothers and sisters on board the passenger (0–8)

* parch -> The number of relatives of the passenger on board (0–6)

* fare -> The amount the passenger paid for the ticket (0–512.3292)

* embarked -> The door through which the passenger boarded the ship (S (Best), C, Q)

/ embark_town -> Port of embarkation of the passenger (C = Cherbourg; Q = Queenstown; S = Southampton)

* deck -> The deck on which the passenger stands ['A', 'B', 'C', 'D', 'E', 'F', 'G']

* alone -> Whether the passenger is alone (True , False)

### getting some feature type information

In [7]:
df.shape

(891, 15)

In [8]:
df.ndim

2

In [9]:
tablo = df.describe(include ='all')
tablo.rename(index = {'count' : 'observations'}, inplace = True)

tablo.loc['null_observations'] = df.isnull().sum()
tablo.loc[['observations', 'null_observations']]

survived  pclass  sex    age  sibsp  parch   fare embarked   
observations          891.0   891.0  891  714.0  891.0  891.0  891.0      889  \
null_observations       0.0     0.0    0  177.0    0.0    0.0    0.0        2   

                  class  who adult_male deck embark_town alive alone  
observations        891  891        891  203         889   891   891  
null_observations     0    0          0  688           2     0     0

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB


In [11]:
titanic = df.drop(['alive', 'class', 'adult_male', 'embark_town'], axis = 1)
titanic

survived  pclass     sex   age  sibsp  parch     fare embarked    who   
0           0       3    male  22.0      1      0   7.2500        S    man  \
1           1       1  female  38.0      1      0  71.2833        C  woman   
2           1       3  female  26.0      0      0   7.9250        S  woman   
3           1       1  female  35.0      1      0  53.1000        S  woman   
4           0       3    male  35.0      0      0   8.0500        S    man   
..        ...     ...     ...   ...    ...    ...      ...      ...    ...   
886         0       2    male  27.0      0      0  13.0000        S    man   
887         1       1  female  19.0      0      0  30.0000        S  woman   
888         0       3  female   NaN      1      2  23.4500        S  woman   
889         1       1    male  26.0      0      0  30.0000        C    man   
890         0       3    male  32.0      0      0   7.7500        Q    man   

    deck  alone  
0    NaN  False  
1      C  False  
2    NaN   True  
3      C  False  
4    NaN   True  
..   ...    ...  
886  NaN   True  
887    B   True  
888  NaN  False  
889    C   True  
890  NaN   True  

[891 rows x 11 columns]

In [12]:
titanic.describe()

survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

### Characteristics of surviving children

In [13]:
titanic['survived'].unique()

array([0, 1], dtype=int64)

In [14]:
titanic['who'].unique()

array(['man', 'woman', 'child'], dtype=object)

In [15]:
((titanic['survived'] == 1) & (titanic['who'] == 'child')).sum()

49

In [16]:
((titanic['survived'] == 1) & (titanic['age'] < 18)).sum()

61

In [17]:
titanic[(titanic['survived'] == 1) & (titanic['who'] == 'child')]

survived  pclass     sex    age  sibsp  parch      fare embarked    who   
9           1       2  female  14.00      1      0   30.0708        C  child  \
10          1       3  female   4.00      1      1   16.7000        S  child   
22          1       3  female  15.00      0      0    8.0292        Q  child   
39          1       3  female  14.00      1      0   11.2417        C  child   
43          1       2  female   3.00      1      2   41.5792        C  child   
58          1       2  female   5.00      1      2   27.7500        S  child   
78          1       2    male   0.83      0      2   29.0000        S  child   
125         1       3    male  12.00      1      0   11.2417        C  child   
165         1       3    male   9.00      0      2   20.5250        S  child   
172         1       3  female   1.00      1      1   11.1333        S  child   
183         1       2    male   1.00      2      1   39.0000        S  child   
184         1       3  female   4.00      0      2   22.0250        S  child   
193         1       2    male   3.00      1      1   26.0000        S  child   
233         1       3  female   5.00      4      2   31.3875        S  child   
237         1       2  female   8.00      0      2   26.2500        S  child   
261         1       3    male   3.00      4      2   31.3875        S  child   
305         1       1    male   0.92      1      2  151.5500        S  child   
340         1       2    male   2.00      1      1   26.0000        S  child   
348         1       3    male   3.00      1      1   15.9000        S  child   
381         1       3  female   1.00      0      2   15.7417        C  child   
407         1       2    male   3.00      1      1   18.7500        S  child   
435         1       1  female  14.00      1      2  120.0000        S  child   
445         1       1    male   4.00      0      2   81.8583        S  child   
446         1       2  female  13.00      0      1   19.5000        S  child   
448         1       3  female   5.00      2      1   19.2583        C  child   
469         1       3  female   0.75      2      1   19.2583        C  child   
479         1       3  female   2.00      0      1   12.2875        S  child   
489         1       3    male   9.00      1      1   15.9000        S  child   
530         1       2  female   2.00      1      1   26.0000        S  child   
535         1       2  female   7.00      0      2   26.2500        S  child   
549         1       2    male   8.00      1      1   36.7500        S  child   
618         1       2  female   4.00      2      1   39.0000        S  child   
644         1       3  female   0.75      2      1   19.2583        C  child   
689         1       1  female  15.00      0      1  211.3375        S  child   
691         1       3  female   4.00      0      1   13.4167        C  child   
720         1       2  female   6.00      0      1   33.0000        S  child   
750         1       2  female   4.00      1      1   23.0000        S  child   
751         1       3    male   6.00      0      1   12.4750        S  child   
755         1       2    male   0.67      1      1   14.5000        S  child   
777         1       3  female   5.00      0      0   12.4750        S  child   
780         1       3  female  13.00      0      0    7.2292        C  child   
788         1       3    male   1.00      1      2   20.5750        S  child   
802         1       1    male  11.00      1      2  120.0000        S  child   
803         1       3    male   0.42      0      1    8.5167        C  child   
827         1       2    male   1.00      0      2   37.0042        C  child   
830         1       3  female  15.00      1      0   14.4542        C  child   
831         1       2    male   0.83      1      1   18.7500        S  child   
869         1       3    male   4.00      1      1   11.1333        S  child   
875         1       3  female  15.00      0      0    7.2250        C  child   

    

In [18]:
titanic[(titanic['survived'] == 1) & (titanic['age'] < 18)]

survived  pclass     sex    age  sibsp  parch     fare embarked    who   
9           1       2  female  14.00      1      0  30.0708        C  child  \
10          1       3  female   4.00      1      1  16.7000        S  child   
22          1       3  female  15.00      0      0   8.0292        Q  child   
39          1       3  female  14.00      1      0  11.2417        C  child   
43          1       2  female   3.00      1      2  41.5792        C  child   
..        ...     ...     ...    ...    ...    ...      ...      ...    ...   
830         1       3  female  15.00      1      0  14.4542        C  child   
831         1       2    male   0.83      1      1  18.7500        S  child   
853         1       1  female  16.00      0      1  39.4000        S  woman   
869         1       3    male   4.00      1      1  11.1333        S  child   
875         1       3  female  15.00      0      0   7.2250        C  child   

    deck  alone  
9    NaN  False  
10     G  False  
22   NaN   True  
39   NaN  False  
43   NaN  False  
..   ...    ...  
830  NaN  False  
831  NaN  False  
853    D  False  
869  NaN  False  
875  NaN   True  

[61 rows x 11 columns]

In [19]:
titanic = df.drop(['alive', 'class', 'adult_male', 'embark_town', 'who'], axis = 1)
titanic

survived  pclass     sex   age  sibsp  parch     fare embarked deck   
0           0       3    male  22.0      1      0   7.2500        S  NaN  \
1           1       1  female  38.0      1      0  71.2833        C    C   
2           1       3  female  26.0      0      0   7.9250        S  NaN   
3           1       1  female  35.0      1      0  53.1000        S    C   
4           0       3    male  35.0      0      0   8.0500        S  NaN   
..        ...     ...     ...   ...    ...    ...      ...      ...  ...   
886         0       2    male  27.0      0      0  13.0000        S  NaN   
887         1       1  female  19.0      0      0  30.0000        S    B   
888         0       3  female   NaN      1      2  23.4500        S  NaN   
889         1       1    male  26.0      0      0  30.0000        C    C   
890         0       3    male  32.0      0      0   7.7500        Q  NaN   

     alone  
0    False  
1    False  
2     True  
3    False  
4     True  
..     ...  
886   True  
887   True  
888  False  
889   True  
890   True  

[891 rows x 10 columns]

In [20]:
titanic['pclass'].unique()

array([3, 1, 2], dtype=int64)

In [21]:
display(((titanic['survived'] == 1) & (titanic['age'] < 18) & (titanic['pclass'] == 1)).sum())
display(((titanic['survived'] == 1) & (titanic['age'] < 18) & (titanic['pclass'] == 2)).sum())
display(((titanic['survived'] == 1) & (titanic['age'] < 18) & (titanic['pclass'] == 3)).sum())

11

21

29

In [22]:
display(((titanic['age'] < 18) & (titanic['pclass'] == 1)).sum())
display(((titanic['age'] < 18) & (titanic['pclass'] == 2)).sum())
display(((titanic['age'] < 18) & (titanic['pclass'] == 3)).sum())

12

23

78

In [23]:
display(((titanic['survived'] == 1) & (titanic['age'] < 18) & (titanic['pclass'] == 1) & (titanic['alone'] == False)).sum())
display(((titanic['survived'] == 1) & (titanic['age'] < 18) & (titanic['pclass'] == 2) & (titanic['alone'] == False)).sum())
display(((titanic['survived'] == 1) & (titanic['age'] < 18) & (titanic['pclass'] == 3) & (titanic['alone'] == False)).sum())

10

19

22

In [24]:
titanic['sibsp'].unique()

array([1, 0, 3, 4, 2, 5, 8], dtype=int64)

In [25]:
titanic['sibsp'].value_counts()

sibsp
0    608
1    209
2     28
4     18
3     16
8      7
5      5
Name: count, dtype: int64

In [26]:
titanic['parch'].unique()

array([0, 1, 2, 5, 3, 4, 6], dtype=int64)

In [27]:
titanic['parch'].value_counts()

parch
0    678
1    118
2     80
5      5
3      5
4      4
6      1
Name: count, dtype: int64